export interface CurrencyDefinition {
    code: string;
    symbol: string;
    name: string;
    locale: string;
}

export const CURRENCIES: Record<string, CurrencyDefinition> = {
    AED: { code: 'AED', symbol: 'dh', name: 'UAE Dirham', locale: 'ar-AE' },
    AFN: { code: 'AFN', symbol: 'Af', name: 'Afghan Afghani', locale: 'fa-AF' },
    ALL: { code: 'ALL', symbol: 'L', name: 'Albanian Lek', locale: 'sq-AL' },
    AMD: { code: 'AMD', symbol: '֏', name: 'Armenian Dram', locale: 'hy-AM' },
    ANG: { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', locale: 'nl-CW' },
    AOA: { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', locale: 'pt-AO' },
    ARS: { code: 'ARS', symbol: '$', name: 'Argentine Peso', locale: 'es-AR' },
    AUD: { code: 'AUD', symbol: '$', name: 'Australian Dollar', locale: 'en-AU' },
    AWG: { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', locale: 'nl-AW' },
    AZN: { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', locale: 'az-AZ' },
    BAM: { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', locale: 'bs-BA' },
    BBD: { code: 'BBD', symbol: '$', name: 'Barbadian Dollar', locale: 'en-BB' },
    BDT: { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', locale: 'bn-BD' },
    BGN: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', locale: 'bg-BG' },
    BHD: { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', locale: 'ar-BH' },
    BIF: { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', locale: 'fr-BI' },
    BMD: { code: 'BMD', symbol: '$', name: 'Bermudan Dollar', locale: 'en-BM' },
    BND: { code: 'BND', symbol: '$', name: 'Brunei Dollar', locale: 'ms-BN' },
    BOB: { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', locale: 'es-BO' },
    BRL: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', locale: 'pt-BR' },
    BSD: { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', locale: 'en-BS' },
    BTC: { code: 'BTC', symbol: '₿', name: 'Bitcoin', locale: 'en-US' },
    BTN: { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', locale: 'dz-BT' },
    BWP: { code: 'BWP', symbol: 'P', name: 'Botswanan Pula', locale: 'en-BW' },
    BYN: { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', locale: 'be-BY' },
    BZD: { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', locale: 'en-BZ' },
    CAD: { code: 'CAD', symbol: '$', name: 'Canadian Dollar', locale: 'en-CA' },
    CDF: { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', locale: 'fr-CD' },
    CHF: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', locale: 'de-CH' },
    CLP: { code: 'CLP', symbol: '$', name: 'Chilean Peso', locale: 'es-CL' },
    CNY: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', locale: 'zh-CN' },
    COP: { code: 'COP', symbol: '$', name: 'Colombian Peso', locale: 'es-CO' },
    CRC: { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', locale: 'es-CR' },
    CUC: { code: 'CUC', symbol: '$', name: 'Cuban Convertible Peso', locale: 'es-CU' },
    CUP: { code: 'CUP', symbol: '₱', name: 'Cuban Peso', locale: 'es-CU' },
    CVE: { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', locale: 'pt-CV' },
    CZK: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', locale: 'cs-CZ' },
    DJF: { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', locale: 'fr-DJ' },
    DKK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone', locale: 'da-DK' },
    DOP: { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', locale: 'es-DO' },
    DZD: { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', locale: 'ar-DZ' },
    EGP: { code: 'EGP', symbol: '£', name: 'Egyptian Pound', locale: 'ar-EG' },
    ERN: { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', locale: 'ti-ER' },
    ETB: { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', locale: 'am-ET' },
    EUR: { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-DE' },
    FJD: { code: 'FJD', symbol: '$', name: 'Fijian Dollar', locale: 'en-FJ' },
    FKP: { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', locale: 'en-FK' },
    GBP: { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
    GEL: { code: 'GEL', symbol: '₾', name: 'Georgian Lari', locale: 'ka-GE' },
    GGP: { code: 'GGP', symbol: '£', name: 'Guernsey Pound', locale: 'en-GG' },
    GHS: { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', locale: 'en-GH' },
    GIP: { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', locale: 'en-GI' },
    GMD: { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', locale: 'en-GM' },
    GNF: { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', locale: 'fr-GN' },
    GTQ: { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', locale: 'es-GT' },
    GYD: { code: 'GYD', symbol: '$', name: 'Guyanaese Dollar', locale: 'en-GY' },
    HKD: { code: 'HKD', symbol: '$', name: 'Hong Kong Dollar', locale: 'zh-HK' },
    HNL: { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', locale: 'es-HN' },
    HRK: { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', locale: 'hr-HR' },
    HTG: { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', locale: 'fr-HT' },
    HUF: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', locale: 'hu-HU' },
    IDR: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', locale: 'id-ID' },
    ILS: { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', locale: 'he-IL' },
    IMP: { code: 'IMP', symbol: '£', name: 'Manx Pound', locale: 'en-IM' },
    INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee', locale: 'en-IN' },
    IQD: { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', locale: 'ar-IQ' },
    IRR: { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', locale: 'fa-IR' },
    ISK: { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', locale: 'is-IS' },
    JEP: { code: 'JEP', symbol: '£', name: 'Jersey Pound', locale: 'en-JE' },
    JMD: { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', locale: 'en-JM' },
    JOD: { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', locale: 'ar-JO' },
    JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', locale: 'ja-JP' },
    KES: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', locale: 'en-KE' },
    KGS: { code: 'KGS', symbol: 'с', name: 'Kyrgystani Som', locale: 'ky-KG' },
    KHR: { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', locale: 'km-KH' },
    KMF: { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', locale: 'fr-KM' },
    KPW: { code: 'KPW', symbol: '₩', name: 'North Korean Won', locale: 'ko-KP' },
    KRW: { code: 'KRW', symbol: '₩', name: 'South Korean Won', locale: 'ko-KR' },
    KWD: { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', locale: 'ar-KW' },
    KYD: { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar', locale: 'en-KY' },
    KZT: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', locale: 'kk-KZ' },
    LAK: { code: 'LAK', symbol: '₭', name: 'Laotian Kip', locale: 'lo-LA' },
    LBP: { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', locale: 'ar-LB' },
    LKR: { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', locale: 'si-LK' },
    LRD: { code: 'LRD', symbol: '$', name: 'Liberian Dollar', locale: 'en-LR' },
    LSL: { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', locale: 'en-LS' },
    LYD: { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', locale: 'ar-LY' },
    MAD: { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', locale: 'ar-MA' },
    MDL: { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', locale: 'ro-MD' },
    MGA: { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', locale: 'mg-MG' },
    MKD: { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', locale: 'mk-MK' },
    MMK: { code: 'MMK', symbol: 'K', name: 'Myanma Kyat', locale: 'my-MM' },
    MNT: { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', locale: 'mn-MN' },
    MOP: { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', locale: 'zh-MO' },
    MRU: { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', locale: 'ar-MR' },
    MUR: { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', locale: 'en-MU' },
    MVR: { code: 'MVR', symbol: '.ރ', name: 'Maldivian Rufiyaa', locale: 'dv-MV' },
    MWK: { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', locale: 'en-MW' },
    MXN: { code: 'MXN', symbol: '$', name: 'Mexican Peso', locale: 'es-MX' },
    MYR: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', locale: 'ms-MY' },
    MZN: { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', locale: 'pt-MZ' },
    NAD: { code: 'NAD', symbol: '$', name: 'Namibian Dollar', locale: 'en-NA' },
    NGN: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', locale: 'en-NG' },
    NIO: { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', locale: 'es-NI' },
    NOK: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', locale: 'nb-NO' },
    NPR: { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', locale: 'ne-NP' },
    NZD: { code: 'NZD', symbol: '$', name: 'New Zealand Dollar', locale: 'en-NZ' },
    OMR: { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', locale: 'ar-OM' },
    PAB: { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', locale: 'es-PA' },
    PEN: { code: 'PEN', symbol: 'S/.', name: 'Peruvian Nuevo Sol', locale: 'es-PE' },
    PGK: { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', locale: 'en-PG' },
    PHP: { code: 'PHP', symbol: '₱', name: 'Philippine Peso', locale: 'en-PH' },
    PKR: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', locale: 'ur-PK' },
    PLN: { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', locale: 'pl-PL' },
    PYG: { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', locale: 'es-PY' },
    QAR: { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Rial', locale: 'ar-QA' },
    RON: { code: 'RON', symbol: 'lei', name: 'Romanian Leu', locale: 'ro-RO' },
    RSD: { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', locale: 'sr-RS' },
    RUB: { code: 'RUB', symbol: '₽', name: 'Russian Ruble', locale: 'ru-RU' },
    RWF: { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', locale: 'rw-RW' },
    SAR: { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', locale: 'ar-SA' },
    SBD: { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar', locale: 'en-SB' },
    SCR: { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', locale: 'en-SC' },
    SDG: { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', locale: 'ar-SD' },
    SEK: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', locale: 'sv-SE' },
    SGD: { code: 'SGD', symbol: '$', name: 'Singapore Dollar', locale: 'en-SG' },
    SHP: { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', locale: 'en-SH' },
    SLL: { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', locale: 'en-SL' },
    SOS: { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', locale: 'so-SO' },
    SRD: { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', locale: 'nl-SR' },
    SSP: { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', locale: 'en-SS' },
    STN: { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', locale: 'pt-ST' },
    SVC: { code: 'SVC', symbol: '$', name: 'Salvadoran Colón', locale: 'es-SV' },
    SYP: { code: 'SYP', symbol: '£', name: 'Syrian Pound', locale: 'ar-SY' },
    SZL: { code: 'SZL', symbol: 'L', name: 'Swazi Lilangeni', locale: 'en-SZ' },
    THB: { code: 'THB', symbol: '฿', name: 'Thai Baht', locale: 'th-TH' },
    TJS: { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', locale: 'tg-TJ' },
    TMT: { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', locale: 'tk-TM' },
    TND: { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', locale: 'ar-TN' },
    TOP: { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', locale: 'to-TO' },
    TRY: { code: 'TRY', symbol: '₺', name: 'Turkish Lira', locale: 'tr-TR' },
    TTD: { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', locale: 'en-TT' },
    TWD: { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', locale: 'zh-TW' },
    TZS: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', locale: 'sw-TZ' },
    UAH: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', locale: 'uk-UA' },
    UGX: { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', locale: 'en-UG' },
    USD: { code: 'USD', symbol: '$', name: 'United States Dollar', locale: 'en-US' },
    UYU: { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', locale: 'es-UY' },
    UZS: { code: 'UZS', symbol: 'лв', name: 'Uzbekistan Som', locale: 'uz-UZ' },
    VES: { code: 'VES', symbol: 'Bs', name: 'Venezuelan Bolívar', locale: 'es-VE' },
    VND: { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', locale: 'vi-VN' },
    VUV: { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', locale: 'bi-VU' },
    WST: { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', locale: 'en-WS' },
    XAF: { code: 'XAF', symbol: 'FCFA', name: 'CFA Franc BEAC', locale: 'fr-XAF' },
    XCD: { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar', locale: 'en-XCD' },
    XOF: { code: 'XOF', symbol: 'CFA', name: 'CFA Franc BCEAO', locale: 'fr-XOF' },
    XPF: { code: 'XPF', symbol: '₣', name: 'CFP Franc', locale: 'fr-XPF' },
    YER: { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', locale: 'ar-YE' },
    ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand', locale: 'en-ZA' },
    ZMW: { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', locale: 'en-ZM' },
    ZWL: { code: 'ZWL', symbol: '$', name: 'Zimbabwean Dollar', locale: 'en-ZW' }
};

export const getCurrencyInfo = (currencyCode: string): CurrencyDefinition => {
    return CURRENCIES[currencyCode] || { code: currencyCode, symbol: currencyCode, name: currencyCode, locale: 'en-US' };
};
